### PR TITLE
feat: airtable oauth2 integration

### PR DESCRIPTION
**Pull request by ybw0014**
## Describe your changes
This PR adds Airtable OAuth2 integration.

Scopes docs: https://airtable.com/developers/web/api/scopes
Airtable example oauth2 workflow: https://github.com/Airtable/oauth-example/blob/main/index.js

## Issue ticket number and link
FI-4
FI-51

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

### CODE REVIEW

**Comment by Charlie059** [comment]
Hi Bowen, for now, the scope can be fixed, we will introduce var when we add Nodes

Ok, we will add a test branch later

**Comment by Charlie059** [comment]
@ybw0014 Hi Bowen, do you test this function to get accesstoken? if yes, I will merge this code

**Review by Charlie059 — APPROVED** [review]
lgtm

**Comment by ybw0014** [comment]
still have some issues, gonna fix it later

**Comment by ybw0014** [comment]
need some extra changes.

**Comment by ybw0014** [comment]
image

**Comment by ybw0014** [comment]
The redirect works as expected, but the callback doesn't seem to print any logs or have a HTTP response? Is that only me or the setup is wrong.

**Comment by Charlie059** [comment]
CacheModule.register() is fantastic!

**Comment by Charlie059** [comment]
> The redirect works as expected, but the callback doesn't seem to print any logs or have a HTTP response? Is that only me or the setup is wrong.

Same error: app-1    | [Nest] 80  - 01/09/2024, 5:02:01 AM   ERROR [AuthCallbackController] Error exchanging code for token

Investigating

**Comment by Charlie059** [comment]
payload looks good:
{"client_id":"xxxxxxxx","client_secret":"xxxxx","redirect_uri":"https://localhost:3000/oauth/callback","grant_type":"authorization_code","code":"xxxxx","code_verifier":"xxxxxx"}

DId you check the official docs?

**Comment by Charlie059** [comment]
app-1    | {"error":"invalid_request","error_description":"The Content-Type of your request must be \"application/x-www-form-urlencoded\"."}

**Comment by Charlie059** [comment]
after add x-www: {"error":"invalid_client","error_description":"Invalid client credentials."}

**Comment by ybw0014** [comment]
The callback is fixed now.

**Comment by Charlie059** [comment]
Is that due to
```
  Authorization: `Basic ${encodedCredentials}`,
 "Content-Type": "application/x-www-form-urlencoded",

```

**Review by Charlie059 — COMMENTED** [review]
lgtm, did you test to refresh token?

**Comment by ybw0014** [comment]
Fixed refresh token, tested and it works.

**Comment by Charlie059** [comment]
many thx!

**Review by Charlie059 — APPROVED** [review]
Thanks! Lgtm

**Pull request merged**
